### ISSUE TITLE
Limit data sets to the current map bounding box

### ISSUE THREAD

**Issue by rafelafrance** [MapofLife/datasets#13]
Filter datasets when the map bounding box changes. Only how datasets that are contained in the bounding box.

**Comment by jmalczyk** [comment]
Apply this as a filter before you do anything else in the UI. So s=zooming
in or out will change the count of datasets in the facet list, and the list
visible under the map. But we need to make it clear that is what is
happening, it could get weird.

**Comment by jmalczyk** [comment]
This behaviour is pretty weird, let's turn it off for now.
