### ISSUE TITLE
Right-clicking on dataset title sends to wrong url

### ISSUE THREAD

**Issue by villanueval** [MapofLife/datasets#2]
Right-click on dataset title and open link in new tab/windows at http://mol.org/datasets/ sends you to 

http://mapoflife.github.io/datasets/info/214f3521-44d8-4c83-a003-e692f2c8ee57

which returns a 404 error instead of 

http://mol.org/datasets/info/214f3521-44d8-4c83-a003-e692f2c8ee57

**Comment by funkycoda** [comment]
There seems to be an issue with the base-url setting. @jmalczyk, do you think you have some ideas here?

**Comment by funkycoda** [comment]
Should now be fixed
