### ISSUE TITLE
Change View Mode text 'Everything'

### ISSUE THREAD

**Issue by rafelafrance** [MapofLife/datasets#22]
Currently says 'Everything', should be 'Both', or something better.

https://3.basecamp.com/3232053/buckets/1126873/todos/179852163

**Comment by jmalczyk** [comment]
We went over this before, but I still feel like the "both" is redundant.
Could we try maybe doing two switches where at least one is forced on? Not
advocating a ui framework (right now anyway) but I really like the material
design ones. https://material.angularjs.org/latest/demo/switch

**Comment by funkycoda** [comment]
I think this is fine for now.

I would only suggest that when the page initially loads, that the "Both" option is actually highlighted (just like when you click it)
