### ISSUE TITLE
Taxonomic group sorting/ordering

### ISSUE THREAD

**Issue by rafelafrance** [MapofLife/datasets#25]
Taxonomic group: As previously requested, let’s put these in more sensible order. And can we group them? Vertebrates, Invertebrates Plants. This way, most folks would be able to the full list. Dodgy that part is hidden now, and requires messing with left hand scroll bar to see.

https://3.basecamp.com/3232053/buckets/1126873/todos/179819577

**Comment by jmalczyk** [comment]
Looks good to me.
