### ISSUE TITLE
Says login/register even when logged in

### ISSUE THREAD

**Issue by villanueval** [MapofLife/datasets#43]
Unlike MapofLife/species#9, I am on https, but it says 'login/register' on top. Showing private datasets, so I'm logged in.

**Comment by funkycoda** [comment]
Working on this

**Comment by funkycoda** [comment]
@rafelafrance, that change breaks the site. I already tried that last week

**Comment by jmalczyk** [comment]
Looks like cross-domain calls are broken now. Getting a blank page at
https://mol.org/datasets/

**Comment by rafelafrance** [comment]
yup... it looks like a problem with the white-list

**Comment by jmalczyk** [comment]
This is not a datasets issue, see https://github.com/MapofLife/mol.org/issues/34
