### ISSUE TITLE
Legend buckets are off by 1

### ISSUE THREAD

**Issue by jmalczyk** [MapofLife/datasets#48]
Looks like the legend is offset by one bucket.
The API  returns the upper bounds of a bucket. So the first bucket value in the legend should read "under xx" and the top end would read "yy-zz" instead of "zz and over".

**Comment by jmalczyk** [comment]
Actually, looking at this closer it seems as if a bin value may be missing in the values the api is returning, but the fix may still require some client side changes.

**Comment by rafelafrance** [comment]
lgtm

**Comment by jmalczyk** [comment]
Fixed by #56
