### ISSUE TITLE
Make visualization types configurable.

### ISSUE THREAD

**Issue by jmalczyk** [MapofLife/datasets#50]
Add an additional field added to the inventory/datasets api that the UI that can allow the UI to determine what map visualizations are available for a given dataset. For example record counts are only appropriate for points.

**Comment by funkycoda** [comment]
ETA
- API: 15 Aug
- UI: 16 Aug

**Comment by villanueval** [comment]
Test available in 0.x.

Points have: `["no_species,no_records"]`

Other datasets have: `["no_species"]`

**Comment by jmalczyk** [comment]
Sorry to add complexity here but we shouldn't lock ourselves into a single visualization type here. map layers are one, but we might also want to add things like charts (histogram across years or uncertainty for example). This works fine for now, but think about how we would restructure this response to be more flexible, something like:

``` json
[
   {"type" : "maps", "options": ["no_species","no_records"]},
   {"type": "histograms", "options": ["years" , "uncertainty"]}
]
```

**Comment by funkycoda** [comment]
@jmalczyk, agreed. This could work. Would be good to know what type of viz features we'd like to add. 

We could potentially use this format for other parts too (e.g. species, indicators, etc)

**Comment by jmalczyk** [comment]
Let's call this done for 0.2. Will file another ticket when we want to add other visualization types.
