### ISSUE TITLE
Add groupBy attribute to facet values

### ISSUE THREAD

**Issue by jmalczyk** [MapofLife/datasets#51]
Facets like taxonomic group need a groupBy attribute that the UI can use to cluster long lists of facets into more appropriate categories

**Comment by funkycoda** [comment]
ETA
- API: 15 Aug
- UI: 17 Aug

**Comment by villanueval** [comment]
Test version on 0.x:

https://api.mol.org/0.x/inventory/datasets

**Comment by funkycoda** [comment]
Looks good @rafelafrance. 
Do you think you can add an icon that shows the toggle state (open/close) like what the other facet types have?

**Comment by funkycoda** [comment]
Much better!! I finally like that the other facet filters' toggle menu is now on the left too. Makes more sense. 

LGTM, so closing for now.
