### ISSUE TITLE
Drop record count column from table view

### ISSUE THREAD

**Issue by jmalczyk** [MapofLife/datasets#52]
This is only appropriate for point datasets, let's drop this field from inventory/datasets for now

**Comment by funkycoda** [comment]
ETA
- API: 15 Aug
- UI: 15 Aug

**Comment by rafelafrance** [comment]
The API has added the "display" attribute and the table now filters on it.

**Comment by villanueval** [comment]
In 1.0 too.

https://api.mol.org/1.0/inventory/datasets

**Comment by funkycoda** [comment]
LGTM
