### ISSUE TITLE
Invertebrates mixed with vertebrates

### ISSUE THREAD

**Issue by villanueval** [MapofLife/datasets#54]
In the Taxonomic Group, we have 
- Butterflies  (11)
- Moths  (2)
- Bumblebees  (2)
- Dragonflies  (7)

The api (https://api.mol.org/0.x/inventory/datasets) seems to be returning the right group for each of these groups. Is it a problem in the way the UI does the grouping or should we re-code this grouping in the API?

**Comment by rafelafrance** [comment]
Changed the filter on the groups to use strict equality

**Comment by villanueval** [comment]
Grouping is correct now. Closing.
