### ISSUE TITLE
Move map layer switchers onto map

### ISSUE THREAD

**Issue by jmalczyk** [MapofLife/datasets#61]
Ideally we these should be a custom control on the map itself, but could use the Leaflet layer switcher as a fallback.

**Comment by jmalczyk** [comment]
Duplicate of #62

**Comment by rafelafrance** [comment]
#Options:
- Preferred: create a custom control for switching layers
- Use the built-in layer control, possibly heavily modified by CSS
- Move the current buttons up (with more css modifications)
