### ISSUE TITLE
Move layer controls into the map itself

### ISSUE THREAD

**Issue by rafelafrance** [MapofLife/datasets#62]
Options:
- Preferred: create a custom control for switching layers
- Use the built-in layer control, possibly heavily modified by CSS
- Move the current buttons up (with heavy CSS modifications)
- Leave them as they are

**Comment by rafelafrance** [comment]
I went with the 3rd option. Custom controls and the built -in layer control needed unreasonable amounts of CSS modification.

**Comment by jmalczyk** [comment]
Should we/could we maybe drop the title on the legend and put these radios
there or just above the legend values? On narrow screens it's easy to miss
the controls over on the bottom right. Otherwise, LGTM

**Comment by funkycoda** [comment]
I agree, the options could go next the the "fullscreen" button (top-right) ?

**Comment by rafelafrance** [comment]
This is doable. However, the legend is a text only control and I had to hack it to get the legend title to work. What I'll do is combine the legend and radio buttons into one new control.

I prefer to keep the legend on the lower left. When you pile up the controls it looks too busy.

**Comment by jmalczyk** [comment]
Could also get messy if/when we add more viz types. But I guess we could
turn it into a dropbox at that point.

**Comment by funkycoda** [comment]
The new "layer control" looks a little better, but I think it's still "gets lost" being right on top of the legend. Maybe make the text stand out? Bolder? bigger font size?

**Comment by rafelafrance** [comment]
How now?

**Comment by funkycoda** [comment]
Much better. Maybe good for now, but we can re-visit this once we switch to Google Maps or if someone says something.
