### ISSUE TITLE
Hide Author and Taxonomic Groups fields that are empty

### ISSUE THREAD

**Issue by jmalczyk** [MapofLife/datasets#65]
These are shown before the model that populates them is filled in. 

https://mol.org/datasets/0002c72a-36fc-4b5e-9c0d-b2d5dbe90779

In general, we should put an ng-if or ng-show on metadata items that uses the value of their model. ng-if will remove that element from the DOM, which may help page performance.

``` html
<div ng-if="item.value">
   <strong ng-bind-html="item.title" />
   <span ng-bind-html="item.value" />
</div>
```

**Comment by funkycoda** [comment]
I thought I added this as an issue, but this should globally encompass all elements. Looking at a blank map with nothing else doesn't make too much sense, from a UX perspective. 

I would suggest the whole loading element should look like what I've added to the Uploader. More specifically, [point-uploader/..../datasets.html#L8-L18](https://github.com/MapofLife/point-uploader/blob/master/loader_app/templates/datasets.html#L8-L18)

**Comment by funkycoda** [comment]
You'll also need to add the necessary CSS and show/hide other elements based on [this](https://github.com/MapofLife/point-uploader/blob/master/loader_app/templates/datasets.html#L35).

**Comment by jmalczyk** [comment]
Also long as there is something spinning tell the user to wait it's fine.
Once we turn on caching for these views this really won't be much of an
issue. Since dataset metadata doesn't change often, there's no reason to
fetch from the database every time.

**Comment by funkycoda** [comment]
LGTM. Closing for now.
