### ISSUE TITLE
/inventory/maps not called in some datasets

### ISSUE THREAD

**Issue by villanueval** [MapofLife/datasets#69]
Testing adding geohashes of updated datasets, I can't seem to get the map to show up. The stats are in the right table, but it seems the /inventory/maps route is not called at all. Am I missing something, is it a cache issue, etc?

https://mol.org/datasets/66607fc8-567f-410a-b613-a64069e0c2ff

![datasets](https://cloud.githubusercontent.com/assets/2302171/18489901/aae2e896-79cd-11e6-8087-760706487e87.png)

**Comment by funkycoda** [comment]
is this a child dataset?

**Comment by villanueval** [comment]
Yeah, forgot to mention that. Would that explain why it is not loading the map?

**Comment by funkycoda** [comment]
I think so. I have noticed this before and I'm sure I mentioned it to @rafelafrance. But can't figure out if I setup an issue. But, in theory, it should be automatic. Unless there is a change in the structure somehow, it's not being triggered. 

Needs a bit more detailed investigation. I'll have a look at it when I get back, so we know why it isn't working.

**Comment by villanueval** [comment]
I'm adding inventories and the map is not showing up. Seems related to this issue since `datasets/maps` is not called in the ones that fail:

https://mol.org/datasets/02f95a33-76db-458c-b7f2-cf904eafdd97

![maps2](https://user-images.githubusercontent.com/2302171/33575414-8f5210aa-d90a-11e7-955e-7c8d1da42a35.png)

One that works, `datasets/maps` got called

https://mol.org/datasets/517b7572-1bf0-43e4-a82b-5358a01654c9

https://api.mol.org/1.x/datasets/maps?callback=angular.callbacks._2&dataset_id=517b7572-1bf0-43e4-a82b-5358a01654c9&property=richness&reducer=max

![maps3](https://user-images.githubusercontent.com/2302171/33575472-c5bb6286-d90a-11e7-8cc3-6147f2ceb109.png)

These are not child datasets. These queries return data that looks ok:

```sql
select * from mol.mol2_data_registry where dataset_id='02f95a33-76db-458c-b7f2-cf904eafdd97';

select * from mol.geohash_summary_stats where dataset_id='02f95a33-76db-458c-b7f2-cf904eafdd97';
```

**Comment by villanueval** [comment]
Seems fixed now. I think the problem was a mismatched field in the dataset metadata (0905simplifiedcompletenessL1.xlsx) or a missing order by value. Refreshed all values and now the datasets page works. 

Closing.
