### ISSUE TITLE
Display a map legend

### ISSUE THREAD

**Issue by funkycoda** [MapofLife/datasets#7]
What is the map even showing?

**Comment by jmalczyk** [comment]
This is # of datasets in the grid cell that meet the selected filter criteria. Here is the map config:

https://github.com/MapofLife/cartodb-named-maps/blob/master/map_config/datasets-map.json

**Comment by jmalczyk** [comment]
WIP by Rafe. The API returns what is needed now...

http://api.mol.org/0.x/inventory/maps?datatype=localinv

``` json
{
   "grid_url": "https://d3dvrpov25vfw0.cloudfront.net/api/v1/map/602f20e3868301e7712f67e5c78504d6:1467740561646:0/0/{z}/{x}/{y}.json", 
   "extent": {"type": "Polygon", "coordinates": [[[-180, -88.59375], [-180, 88.59375], [180, 88.59375], [180, -88.59375], [-180, -88.59375]]]}, 
   "tile_url": "https://d3dvrpov25vfw0.cloudfront.net/api/v1/map/602f20e3868301e7712f67e5c78504d6:1467740561646:0/{z}/{x}/{y}.png", 
   "legend": {
      "colors": ["#0C2C84", "#225EA8", "#1D91C0", "#41B6C4", "#7FCDBB", "#C7E9B4", "#FFDDCC", "#FFFFDD"], 
      "bins": [2, 2, 3, 3, 5, 10, 24]
   }
}
```

**Comment by jmalczyk** [comment]
Legend looks good, but lets get it showing on the single dataset view too.

**Comment by rafelafrance** [comment]
Why? There's only one dataset. We're telling the user nothing and using up map real-estate. I specifically removed it for that reason.

**Comment by jmalczyk** [comment]
If the metric is dataset count, but we will be adding species richness and
record count soon. Once we do, we can switch off the dataset count metric
for that view.

**Comment by rafelafrance** [comment]
I put in some extra logic to get rid the excess legend entries.
