### ISSUE TITLE
Point occurrences not showing

### ISSUE THREAD

**Issue by mduong7** [MapofLife/datasets#77]
Both in datasets and datasets-dev, only data types showing are:
Regional checklists
Local Inventories
Expert range maps
Gridded surveys

**Comment by funkycoda** [comment]
Probably waiting on the metadata to be made live. This is database related so you might want to open the issue there.

**Comment by jmalczyk** [comment]
More likely geohash generation related. For big point datasets we might
want to move this to BigQuery.

**Comment by villanueval** [comment]
Needed to improve the script that generates these stats, it was choking on large datasets (MapofLife/database#527). It works better now, just need to run on the missing datasets.

**Comment by villanueval** [comment]
Point datasets now showing. I'm adding more every day.

Closing issue.
