### ISSUE TITLE
Add # of records

### ISSUE THREAD

**Issue by villanueval** [MapofLife/datasets#79]
We removed the display of # of records per dataset. Test if this is fast enough or if we need to store the value, maybe in `mol2_data_registry` and add it to `mol.org/datasets`.

**Comment by funkycoda** [comment]
Did this have the `No. of datasets` before? I wonder if we should bring it back with a pre-computed value

**Comment by villanueval** [comment]
We did. I want to test if its best to calculate on the fly or store the val and then editing the query accordingly.

**Comment by villanueval** [comment]
Now shows the number of records. Closing.
