### ISSUE TITLE
Footer in middle of page

### ISSUE THREAD

**Issue by villanueval** [MapofLife/datasets#8]
https://mol.org/datasets/f607ed3d-fe0c-4367-b4b9-3d056763e43e
- The footer is stuck in the middle of the page instead of sticking to the bottom
- ~~Section headings are repeating (General, Geospatial, Taxonomy)~~

**Comment by villanueval** [comment]
Repeated section headings is a problem in the API. Fixed.

**Comment by villanueval** [comment]
Footer in the middle of page:

![footer](https://cloud.githubusercontent.com/assets/2302171/16591937/480b6e58-42ac-11e6-911c-a0fb36d934bf.png)

**Comment by villanueval** [comment]
Fixed

**Comment by funkycoda** [comment]
This looks like it's back again. Maybe related to the change you did for #38, @rafelafrance  ? 

http://mol.org/datasets/fe4b9fd2-7da6-46b8-8bef-754044461210

**Comment by rafelafrance** [comment]
fixed
