### ISSUE TITLE
Metadata area too small

### ISSUE THREAD

**Issue by villanueval** [MapofLife/datasets#9]
Looking in a small-ish screen, area of the text is too small. Plus, footer is moving from the bottom.

![smscreen](https://cloud.githubusercontent.com/assets/2302171/16656120/6d30a754-442b-11e6-9282-b9e832614dd6.png)

**Comment by jmalczyk** [comment]
This will become a full scroll, and the map size should probably respond to
screen size.

**Comment by funkycoda** [comment]
I have the same issue as @ljvillanueva. I believe the solution should also target the full list view as well.
